# Generated by Django 3.0.2 on 2020-01-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_IRIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lkvertical',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbindicadoresagente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='validaftagg',
            options={'managed': True},
        ),
    ]
